### ISSUE TITLE
2020.2 doesnt seem to have specified versal device

### ISSUE THREAD

**Issue by jue-s** [Xilinx-Wiki-Projects/VCK190-Ethernet#4]
trying to get the vivado design with instructions from https://github.com/Xilinx-Wiki-Projects/VCK190-Ethernet/tree/master/2020.2/pl_eth_1G

but even with 2020.2.2, i get this error:

WARNING: [Device 21-436] No parts matched 'xcvc1902-vsva2197-2MP-e-S-es1'
ERROR: [Coretcl 2-106] Specified part could not be fou

**Comment by ajayadaha1** [comment]
The new pull request solves this error. Please approve and merge to master.

**Comment by nan-zang** [comment]
The issue has been resolved.
